num = 3
try: 
    #code that may raise an exception 
    x = 3/num
    print(x)
except:
    #Exception  occurs, if code under try throws error
    print("An exception occurred")

